services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    ports:
      - "1433:1433"
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: "no"

volumes:
  sqlserver_data:
