
namespace KlijentWFA
{
    partial class Main
    {
        private System.ComponentModel.IContainer components = null;

        private System.Windows.Forms.Panel pnlTop;
        private System.Windows.Forms.Label lblAppTitle;

        private System.Windows.Forms.Panel pnlSidebar;
        private System.Windows.Forms.Panel pnlSearchWrap;
        private System.Windows.Forms.TextBox txtSearch;

        private System.Windows.Forms.Panel pnlTabBar;
        private System.Windows.Forms.Button btnRazgovori;
        private System.Windows.Forms.Button btnPrijatelji;

        private System.Windows.Forms.Panel pnlContent;
        private System.Windows.Forms.RichTextBox rtbChat;

        private System.Windows.Forms.Panel pnlComposer;
        private System.Windows.Forms.Panel pnlMessageWrap;
        private System.Windows.Forms.TextBox txtMessage;
        private System.Windows.Forms.Button btnPosalji;

        private System.Windows.Forms.DataGridView dgv_razgovori;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRazgovorUser;
        private System.Windows.Forms.DataGridViewButtonColumn colRazgovorOdbij;

        private System.Windows.Forms.DataGridView dgv_prijatelji;
        private System.Windows.Forms.DataGridViewTextBoxColumn colFriendUser;
        private System.Windows.Forms.DataGridViewButtonColumn colAccept;
        private System.Windows.Forms.DataGridViewButtonColumn colDecline;

        private System.Windows.Forms.Button search_btn;
        private System.Windows.Forms.Timer update_thr;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            pnlTop = new Panel();
            lblAppTitle = new Label();
            pnlSidebar = new Panel();
            dgv_prijatelji = new DataGridView();
            colFriendUser = new DataGridViewTextBoxColumn();
            colAccept = new DataGridViewButtonColumn();
            colDecline = new DataGridViewButtonColumn();
            dgv_razgovori = new DataGridView();
            colRazgovorUser = new DataGridViewTextBoxColumn();
            colRazgovorOdbij = new DataGridViewButtonColumn();
            pnlTabBar = new Panel();
            btnPrijatelji = new Button();
            btnRazgovori = new Button();
            pnlSearchWrap = new Panel();
            search_btn = new Button();
            txtSearch = new TextBox();
            pnlContent = new Panel();
            rtbChat = new RichTextBox();
            pnlComposer = new Panel();
            btnPosalji = new Button();
            pnlMessageWrap = new Panel();
            txtMessage = new TextBox();
            update_thr = new System.Windows.Forms.Timer(components);
            pnlTop.SuspendLayout();
            pnlSidebar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgv_prijatelji).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgv_razgovori).BeginInit();
            pnlTabBar.SuspendLayout();
            pnlSearchWrap.SuspendLayout();
            pnlContent.SuspendLayout();
            pnlComposer.SuspendLayout();
            pnlMessageWrap.SuspendLayout();
            SuspendLayout();
            pnlTop.BackColor = Color.FromArgb(14, 14, 15);
            pnlTop.Controls.Add(lblAppTitle);
            pnlTop.Dock = DockStyle.Top;
            pnlTop.Location = new Point(0, 0);
            pnlTop.Name = "pnlTop";
            pnlTop.Size = new Size(1118, 52);
            pnlTop.TabIndex = 0;
            lblAppTitle.Dock = DockStyle.Left;
            lblAppTitle.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
            lblAppTitle.ForeColor = Color.Gainsboro;
            lblAppTitle.Location = new Point(0, 0);
            lblAppTitle.Name = "lblAppTitle";
            lblAppTitle.Padding = new Padding(16, 0, 0, 0);
            lblAppTitle.Size = new Size(240, 52);
            lblAppTitle.TabIndex = 0;
            lblAppTitle.Text = "Chat Klijent";
            lblAppTitle.TextAlign = ContentAlignment.MiddleLeft;
            pnlSidebar.BackColor = Color.FromArgb(16, 16, 17);
            pnlSidebar.Controls.Add(dgv_prijatelji);
            pnlSidebar.Controls.Add(dgv_razgovori);
            pnlSidebar.Controls.Add(pnlTabBar);
            pnlSidebar.Controls.Add(pnlSearchWrap);
            pnlSidebar.Dock = DockStyle.Left;
            pnlSidebar.Location = new Point(0, 52);
            pnlSidebar.Name = "pnlSidebar";
            pnlSidebar.Padding = new Padding(14);
            pnlSidebar.Size = new Size(300, 509);
            pnlSidebar.TabIndex = 1;
            dgv_prijatelji.AllowUserToAddRows = false;
            dgv_prijatelji.AllowUserToDeleteRows = false;
            dgv_prijatelji.AllowUserToResizeColumns = false;
            dgv_prijatelji.AllowUserToResizeRows = false;
            dgv_prijatelji.BackgroundColor = Color.FromArgb(18, 18, 19);
            dgv_prijatelji.BorderStyle = BorderStyle.None;
            dgv_prijatelji.CellBorderStyle = DataGridViewCellBorderStyle.None;
            dgv_prijatelji.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dgv_prijatelji.ColumnHeadersVisible = false;
            dgv_prijatelji.Columns.AddRange(new DataGridViewColumn[] { colFriendUser, colAccept, colDecline });
            dataGridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(18, 18, 19);
            dataGridViewCellStyle1.Font = new Font("Segoe UI", 9.5F);
            dataGridViewCellStyle1.ForeColor = Color.Gainsboro;
            dataGridViewCellStyle1.SelectionBackColor = Color.FromArgb(30, 30, 32);
            dataGridViewCellStyle1.SelectionForeColor = Color.Gainsboro;
            dataGridViewCellStyle1.WrapMode = DataGridViewTriState.False;
            dgv_prijatelji.DefaultCellStyle = dataGridViewCellStyle1;
            dgv_prijatelji.Dock = DockStyle.Fill;
            dgv_prijatelji.EnableHeadersVisualStyles = false;
            dgv_prijatelji.GridColor = Color.FromArgb(18, 18, 19);
            dgv_prijatelji.Location = new Point(14, 96);
            dgv_prijatelji.MultiSelect = false;
            dgv_prijatelji.Name = "dgv_prijatelji";
            dgv_prijatelji.ReadOnly = true;
            dgv_prijatelji.RowHeadersVisible = false;
            dgv_prijatelji.RowTemplate.Height = 38;
            dgv_prijatelji.ScrollBars = ScrollBars.Vertical;
            dgv_prijatelji.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv_prijatelji.Size = new Size(272, 399);
            dgv_prijatelji.TabIndex = 3;
            dgv_prijatelji.Visible = false;
            dgv_prijatelji.CellContentClick += dgv_prijatelji_CellContentClick;
            colFriendUser.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            colFriendUser.DataPropertyName = "Korisnicko_ime";
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.FromArgb(18, 18, 19);
            dataGridViewCellStyle2.ForeColor = Color.Gainsboro;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(30, 30, 32);
            dataGridViewCellStyle2.SelectionForeColor = Color.Gainsboro;
            colFriendUser.DefaultCellStyle = dataGridViewCellStyle2;
            colFriendUser.Name = "colFriendUser";
            colFriendUser.ReadOnly = true;
            colAccept.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            colAccept.FlatStyle = FlatStyle.Flat;
            colAccept.Name = "colAccept";
            colAccept.ReadOnly = true;
            colAccept.Text = "Accept";
            colAccept.UseColumnTextForButtonValue = true;
            colAccept.Width = 82;
            colDecline.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            colDecline.FlatStyle = FlatStyle.Flat;
            colDecline.Name = "colDecline";
            colDecline.ReadOnly = true;
            colDecline.Text = "Decline";
            colDecline.UseColumnTextForButtonValue = true;
            colDecline.Width = 82;
            dgv_razgovori.AllowUserToAddRows = false;
            dgv_razgovori.AllowUserToDeleteRows = false;
            dgv_razgovori.AllowUserToResizeColumns = false;
            dgv_razgovori.AllowUserToResizeRows = false;
            dgv_razgovori.BackgroundColor = Color.FromArgb(18, 18, 19);
            dgv_razgovori.BorderStyle = BorderStyle.None;
            dgv_razgovori.CellBorderStyle = DataGridViewCellBorderStyle.None;
            dgv_razgovori.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dgv_razgovori.ColumnHeadersVisible = false;
            dgv_razgovori.Columns.AddRange(new DataGridViewColumn[] { colRazgovorUser, colRazgovorOdbij });
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.FromArgb(18, 18, 19);
            dataGridViewCellStyle3.Font = new Font("Segoe UI", 9.5F);
            dataGridViewCellStyle3.ForeColor = Color.Gainsboro;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(30, 30, 32);
            dataGridViewCellStyle3.SelectionForeColor = Color.Gainsboro;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgv_razgovori.DefaultCellStyle = dataGridViewCellStyle3;
            dgv_razgovori.Dock = DockStyle.Fill;
            dgv_razgovori.EnableHeadersVisualStyles = false;
            dgv_razgovori.GridColor = Color.FromArgb(18, 18, 19);
            dgv_razgovori.Location = new Point(14, 96);
            dgv_razgovori.MultiSelect = false;
            dgv_razgovori.Name = "dgv_razgovori";
            dgv_razgovori.ReadOnly = true;
            dgv_razgovori.RowHeadersVisible = false;
            dgv_razgovori.RowTemplate.Height = 38;
            dgv_razgovori.ScrollBars = ScrollBars.Vertical;
            dgv_razgovori.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv_razgovori.Size = new Size(272, 399);
            dgv_razgovori.TabIndex = 2;
            dgv_razgovori.CellContentClick += dgv_razgovori_CellContentClick;
            colRazgovorUser.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            colRazgovorUser.DataPropertyName = "Korisnicko_ime";
            dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = Color.FromArgb(18, 18, 19);
            dataGridViewCellStyle4.ForeColor = Color.Gainsboro;
            dataGridViewCellStyle4.SelectionBackColor = Color.FromArgb(30, 30, 32);
            dataGridViewCellStyle4.SelectionForeColor = Color.Gainsboro;
            colRazgovorUser.DefaultCellStyle = dataGridViewCellStyle4;
            colRazgovorUser.Name = "colRazgovorUser";
            colRazgovorUser.ReadOnly = true;
            colRazgovorOdbij.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
            colRazgovorOdbij.FlatStyle = FlatStyle.Flat;
            colRazgovorOdbij.Name = "colRazgovorOdbij";
            colRazgovorOdbij.ReadOnly = true;
            colRazgovorOdbij.Text = "Odbij";
            colRazgovorOdbij.UseColumnTextForButtonValue = true;
            colRazgovorOdbij.Width = 82;
            pnlTabBar.BackColor = Color.FromArgb(16, 16, 17);
            pnlTabBar.Controls.Add(btnPrijatelji);
            pnlTabBar.Controls.Add(btnRazgovori);
            pnlTabBar.Dock = DockStyle.Top;
            pnlTabBar.Location = new Point(14, 45);
            pnlTabBar.Name = "pnlTabBar";
            pnlTabBar.Size = new Size(272, 51);
            pnlTabBar.TabIndex = 1;
            btnPrijatelji.BackColor = Color.FromArgb(16, 16, 17);
            btnPrijatelji.FlatAppearance.BorderSize = 0;
            btnPrijatelji.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 20, 21);
            btnPrijatelji.FlatAppearance.MouseOverBackColor = Color.FromArgb(20, 20, 21);
            btnPrijatelji.FlatStyle = FlatStyle.Flat;
            btnPrijatelji.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnPrijatelji.ForeColor = Color.FromArgb(150, 150, 152);
            btnPrijatelji.Location = new Point(142, 6);
            btnPrijatelji.Name = "btnPrijatelji";
            btnPrijatelji.Size = new Size(127, 40);
            btnPrijatelji.TabIndex = 1;
            btnPrijatelji.Text = "Prijatelji";
            btnPrijatelji.UseVisualStyleBackColor = false;
            btnPrijatelji.Click += btnPrijatelji_Click;
            btnRazgovori.FlatAppearance.BorderSize = 0;
            btnRazgovori.FlatAppearance.MouseDownBackColor = Color.FromArgb(20, 20, 21);
            btnRazgovori.FlatAppearance.MouseOverBackColor = Color.FromArgb(20, 20, 21);
            btnRazgovori.FlatStyle = FlatStyle.Flat;
            btnRazgovori.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnRazgovori.ForeColor = Color.Gainsboro;
            btnRazgovori.Location = new Point(3, 6);
            btnRazgovori.Name = "btnRazgovori";
            btnRazgovori.Size = new Size(127, 40);
            btnRazgovori.TabIndex = 0;
            btnRazgovori.Text = "Razgovori";
            btnRazgovori.UseVisualStyleBackColor = true;
            btnRazgovori.Click += btnRazgovori_Click;
            pnlSearchWrap.BackColor = Color.FromArgb(22, 22, 23);
            pnlSearchWrap.Controls.Add(search_btn);
            pnlSearchWrap.Controls.Add(txtSearch);
            pnlSearchWrap.Dock = DockStyle.Top;
            pnlSearchWrap.Location = new Point(14, 14);
            pnlSearchWrap.Name = "pnlSearchWrap";
            pnlSearchWrap.Padding = new Padding(12, 10, 12, 10);
            pnlSearchWrap.Size = new Size(272, 31);
            pnlSearchWrap.TabIndex = 0;
            search_btn.FlatAppearance.BorderSize = 0;
            search_btn.FlatStyle = FlatStyle.Flat;
            search_btn.ForeColor = SystemColors.ButtonHighlight;
            search_btn.Location = new Point(3, 3);
            search_btn.Name = "search_btn";
            search_btn.Size = new Size(23, 23);
            search_btn.TabIndex = 1;
            search_btn.Text = "⌕";
            search_btn.UseVisualStyleBackColor = true;
            search_btn.Click += search_btn_Click;
            txtSearch.BackColor = Color.FromArgb(22, 22, 23);
            txtSearch.BorderStyle = BorderStyle.None;
            txtSearch.Font = new Font("Segoe UI", 10F);
            txtSearch.ForeColor = Color.Gainsboro;
            txtSearch.Location = new Point(31, 6);
            txtSearch.Name = "txtSearch";
            txtSearch.Size = new Size(226, 18);
            txtSearch.TabIndex = 0;
            pnlContent.BackColor = Color.FromArgb(12, 12, 13);
            pnlContent.Controls.Add(rtbChat);
            pnlContent.Controls.Add(pnlComposer);
            pnlContent.Dock = DockStyle.Fill;
            pnlContent.Location = new Point(300, 52);
            pnlContent.Name = "pnlContent";
            pnlContent.Padding = new Padding(18);
            pnlContent.Size = new Size(818, 509);
            pnlContent.TabIndex = 2;
            rtbChat.BackColor = Color.FromArgb(18, 18, 19);
            rtbChat.BorderStyle = BorderStyle.None;
            rtbChat.Dock = DockStyle.Fill;
            rtbChat.Font = new Font("Segoe UI", 10F);
            rtbChat.ForeColor = Color.Gainsboro;
            rtbChat.Location = new Point(18, 18);
            rtbChat.Name = "rtbChat";
            rtbChat.ReadOnly = true;
            rtbChat.Size = new Size(782, 405);
            rtbChat.TabIndex = 0;
            rtbChat.Text = "";
            pnlComposer.BackColor = Color.FromArgb(12, 12, 13);
            pnlComposer.Controls.Add(btnPosalji);
            pnlComposer.Controls.Add(pnlMessageWrap);
            pnlComposer.Dock = DockStyle.Bottom;
            pnlComposer.Location = new Point(18, 423);
            pnlComposer.Name = "pnlComposer";
            pnlComposer.Size = new Size(782, 68);
            pnlComposer.TabIndex = 1;
            btnPosalji.BackColor = Color.MidnightBlue;
            btnPosalji.FlatAppearance.BorderSize = 0;
            btnPosalji.FlatAppearance.MouseDownBackColor = Color.FromArgb(37, 99, 235);
            btnPosalji.FlatAppearance.MouseOverBackColor = Color.FromArgb(79, 148, 255);
            btnPosalji.FlatStyle = FlatStyle.Flat;
            btnPosalji.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold);
            btnPosalji.ForeColor = Color.White;
            btnPosalji.Location = new Point(646, 14);
            btnPosalji.Name = "btnPosalji";
            btnPosalji.Size = new Size(118, 40);
            btnPosalji.TabIndex = 1;
            btnPosalji.Text = "Pošalji";
            btnPosalji.UseVisualStyleBackColor = false;
            pnlMessageWrap.BackColor = Color.FromArgb(22, 22, 23);
            pnlMessageWrap.Controls.Add(txtMessage);
            pnlMessageWrap.Location = new Point(3, 14);
            pnlMessageWrap.Name = "pnlMessageWrap";
            pnlMessageWrap.Padding = new Padding(12, 11, 12, 11);
            pnlMessageWrap.Size = new Size(633, 40);
            pnlMessageWrap.TabIndex = 0;
            txtMessage.BackColor = Color.FromArgb(22, 22, 23);
            txtMessage.BorderStyle = BorderStyle.None;
            txtMessage.Font = new Font("Segoe UI", 10F);
            txtMessage.ForeColor = Color.Gainsboro;
            txtMessage.Location = new Point(12, 11);
            txtMessage.Name = "txtMessage";
            txtMessage.Size = new Size(612, 18);
            txtMessage.TabIndex = 0;
            update_thr.Interval = 1000;
            update_thr.Tick += update_thr_Tick;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(12, 12, 13);
            ClientSize = new Size(1118, 561);
            Controls.Add(pnlContent);
            Controls.Add(pnlSidebar);
            Controls.Add(pnlTop);
            MinimumSize = new Size(980, 600);
            Name = "Main";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Main";
            pnlTop.ResumeLayout(false);
            pnlSidebar.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgv_prijatelji).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgv_razgovori).EndInit();
            pnlTabBar.ResumeLayout(false);
            pnlSearchWrap.ResumeLayout(false);
            pnlSearchWrap.PerformLayout();
            pnlContent.ResumeLayout(false);
            pnlComposer.ResumeLayout(false);
            pnlMessageWrap.ResumeLayout(false);
            pnlMessageWrap.PerformLayout();
            ResumeLayout(false);
        }

      
    }
}
